@host = http://localhost:8000

GET {{host}}/users

###


# @name CreateUser
POST {{host}}/users
Content-Type: application/json

{
  "username": "{{$randomInt 2 9000}}_bob@gmail.com",
  "password": "randomm password",
  "public_key": "public key",
  "private_key": "private key"
}


###

@userid = {{CreateUser.response.body.ID}}

GET {{host}}/users/{{userid}}
Content-Type: application/json

###


PATCH {{host}}/users/{{userid}}
Content-Type: application/json

{
  "username": "steve"
}

###


DELETE {{host}}/users/{{userid}}

###
